##########################################################
#
#  USER DEFINED INPUT
#
##########################################################

figtag: 'bulkaero'
varlist: ['aod','aaod']

y0: 2003
yf: 2008

ens_models: ['CanESM51-p2']
ens_expts:  ['historical']

ind_models: ['CanAM-bulk','CanAM-bulk']
ind_runids: ['v52rc0-amip','bulkaero2-aya']

models_to_map: ['CanAM-bulk']
modeltags_to_map: ['bulkaero2-aya']

