##########################################################
#
#  USER DEFINED INPUT
#
##########################################################

figtag: 'PAMtuning'
varlist: ['aod','aaod','dod','ae']

y0: 2014
yf: 2015

ens_models: []
ens_expts:  []

ind_models: ['CanAM-PAM','CanAM-PAM','CanAM-PAM']
ind_runids: ['pam12-aya','pam16-aya','aerotune1-aya']

models_to_map: ['CanAM-PAM']
modeltags_to_map: ['pam16-aya']

